apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
  namespace: tasky
spec:
# everyday at midnight 
  schedule: "0 0 * * *"  
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup
            image: mongo:5.0
            command: ["/bin/sh", "-c"]
            args:
            - |
              apt-get update && \
              apt-get install -y curl unzip && \
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
              unzip awscliv2.zip && \
              ./aws/install && \
              mongodump --uri="mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017" --archive=/backup/mongodb-$(date +%F).gz --gzip && \
              aws s3 cp /backup/mongodb-$(date +%F).gz s3://backup-bucket-jls-wiz/
            env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret-key
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
          volumes:
          - name: backup-storage
            emptyDir: {}